name: ExtractionRegionEditor
version: "${project.version}"
main: com.criztiandev.extractionregion.ExtractionRegionPlugin
api-version: "1.21"
author: criztiandev
description: Advanced region and timer management for ExtractionChest.
depend: [ExtractionChest]
website: https://github.com/criztiandev/extraction-region-editor

commands:
  regioneditor:
    description: Main command for ExtractionRegionEditor.
    usage: /regioneditor [args]
    aliases: [re, lr]
  regionchest:
    description: Open the chest region menu.
    usage: /regionchest
    aliases: [lrc]
  regionentry:
    description: Open the entry region menu.
    usage: /regionentry
    aliases: [lre]
  regionexit:
    description: Open the extraction region menu.
    usage: /regionexit
    aliases: [lrex]
